server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # ЦЕ ВИПРАВИТЬ 404 ПРИ ПЕРЕЗАВАНТАЖЕННІ ПІЦУШІ
        try_files $uri $uri/ /index.html;
    }
}
